version: "3.3"

services:
  spotimongodb:
    image: mongo:latest
    container_name: spotimongodb
    restart: always
    volumes:
      - spoti-vol:/data/db
  spotibackend:
    build: .
    container_name: spotibackend
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://spotimongodb:27017/spotifyClone
      - PORT=5000     
    depends_on:
      - spotimongodb
  spotifrontend:
    build: ../client/spotify_front
    container_name: spotifrontend
    ports:
      - 3000:3000
    stdin_open: true 
    tty: true 
    volumes:
      - ../client/spotify_front:/app
    depends_on:
      - spotibackend         

volumes:
    spoti-vol: {}

